language: node_js
sudo: false
dist: trusty

node_js:
  - "10.1"
  - "10.0"
  - "9.11"
  - "9.10"
  - "9.9"
  - "9.8"
  - "9.7"
  - "9.6"
  - "9.5"
  - "9.4"
  - "9.3"
  - "9.2"
  - "9.1"
  - "9.0"
  - 8
  - 7
  - 6

os: linux

stages:
  - test

before_install:
  - stty cols 130

script: "npm test"

jobs:
  fast_finish: true
